version: '3.8'

services:
  ipfs0:
    image: ipfs/kubo:release
    container_name: ${IPFS_NODE}
    ports:
      - "4001:4001"  # Swarm
      - "5001:5001"  # API
      - "8080:8080"  # Gateway
    volumes:
      - ./compose/${IPFS_NODE}:/data/ipfs

  cluster0:
    image: ipfs/ipfs-cluster:latest
    container_name: ${CLUSTER_NODE}
    ports:
      - "9097:9094"  # REST API
      - "9096:9096"  # Cluster communication
    environment:
      CLUSTER_PEERNAME: ${CLUSTER_NODE}
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs0/tcp/5001
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s
    volumes:
      - ./compose/${CLUSTER_NODE}:/data/ipfs-cluster
    depends_on:
      - ipfs0
